_wandb:
    value:
        cli_version: 0.22.3
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.9.25
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
epoch:
    value: 50
lr:
    value: 0.0001
